const registry = require('../registry')

// 1. Nạp các handlers thực tế có file code
const postPageHandler = require('./post-page')
const postPageGraphHandler = require('./post-page-graph')
const postGroupHandler = require('./post-group')
const postProfileHandler = require('./post-profile')
const checkHealthHandler = require('./check-health')
const fetchPagesHandler = require('./fetch-pages')
const fetchGroupsHandler = require('./fetch-groups')
const fetchAllHandler = require('./fetch-all')
const resolveGroupHandler = require('./resolve-group')
const checkEngagementHandler = require('./check-engagement')
const scanGroupFeedHandler = require('./scan-group-feed')
const commentPostHandler = require('./comment-post')
const joinGroupHandler = require('./join-group')

// Campaign role handlers (Sprint 3)
const campaignDiscoverGroupsHandler = require('./campaign-discover-groups')
const campaignNurtureHandler = require('./campaign-nurture')
const campaignSendFriendRequestHandler = require('./campaign-send-friend-request')
const campaignInteractProfileHandler = require('./campaign-interact-profile')
const campaignPostHandler = require('./campaign-post')
const campaignGroupMonitorHandler = require('./campaign-group-monitor')
const campaignOpportunityReactHandler = require('./campaign-opportunity-react')
const nurtureFeedHandler = require('./nurture-feed')
const checkGroupMembershipHandler = require('./check-group-membership')
const fetchSourceCookieHandler = require('./fetch-source-cookie')
const scanGroupHandler = require('./scan-group')

// 2. Đăng ký các handlers thực tế
registry.register('post_page', postPageHandler, { isPostType: true, label: 'Đăng trang', icon: '📄' })
registry.register('post_page_graph', postPageGraphHandler, { isPostType: true, needsBrowser: false, isUtility: true, label: 'Đăng trang qua Graph API', icon: '🌐' })
registry.register('post_group', postGroupHandler, { isPostType: true, label: 'Đăng bài nhóm', icon: '👥' })
registry.register('post_profile', postProfileHandler, { isPostType: true, label: 'Đăng trang cá nhân', icon: '👤' })
registry.register('check_health', checkHealthHandler, { isUtility: true, label: 'Kiểm tra tài khoản', icon: '🏥' })
registry.register('fetch_pages', fetchPagesHandler, { isUtility: true, label: 'Đồng bộ danh sách trang', icon: '📄' })
registry.register('fetch_groups', fetchGroupsHandler, { isUtility: true, label: 'Đồng bộ danh sách nhóm', icon: '👥' })
registry.register('fetch_all', fetchAllHandler, { isUtility: true, label: 'Đồng bộ toàn bộ dữ liệu', icon: '🔄' })
registry.register('resolve_group', resolveGroupHandler, { isUtility: true, label: 'Giải quyết thông tin nhóm', icon: '🔍' })
registry.register('check_engagement', checkEngagementHandler, { isUtility: true, label: 'Kiểm tra tương tác', icon: '📊' })
registry.register('scan_group_feed', scanGroupFeedHandler, { isUtility: true, label: 'Quét bài viết nhóm', icon: '📡' })
registry.register('comment_post', commentPostHandler, { label: 'Bình luận bài viết', icon: '💬' })
registry.register('join_group', joinGroupHandler, { label: 'Tham gia nhóm', icon: '🤝' })
registry.register('campaign_discover_groups', campaignDiscoverGroupsHandler, { label: 'Khám phá nhóm chiến dịch', icon: '🧭' })
registry.register('campaign_nurture', campaignNurtureHandler, { label: 'Tương tác chiến dịch', icon: '🌱' })
registry.register('campaign_send_friend_request', campaignSendFriendRequestHandler, { label: 'Gửi lời mời kết bạn', icon: '👥' })
registry.register('campaign_interact_profile', campaignInteractProfileHandler, { label: 'Tương tác trang cá nhân', icon: '👤' })
registry.register('campaign_post', campaignPostHandler, { isPostType: true, label: 'Đăng bài chiến dịch', icon: '📝' })
registry.register('campaign_group_monitor', campaignGroupMonitorHandler, { isUtility: true, label: 'Giám sát nhóm chiến dịch', icon: '🛡️' })
registry.register('campaign_opportunity_react', campaignOpportunityReactHandler, { label: 'Phản hồi cơ hội chiến dịch', icon: '⚡' })
registry.register('nurture_feed', nurtureFeedHandler, { isUtility: true, label: 'Tương tác nuôi nick', icon: '🌾' })
registry.register('check_group_membership', checkGroupMembershipHandler, { isUtility: true, label: 'Kiểm tra thành viên nhóm', icon: '🔍' })
registry.register('fetch_source_cookie', fetchSourceCookieHandler, { isUtility: true, label: 'Lấy cookie nguồn', icon: '🍪' })
registry.register('scan_group', scanGroupHandler, { isUtility: true, label: 'Do thám nhóm', icon: '🕵️' })

// 3. Đăng ký các job types cũ/chưa cài đặt code (để làm Single Source of Truth cho các hằng số ở poller)
// (Unimplemented in this standalone agent version)

module.exports = registry
