// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ApplyUpdate():Promise<{[key: string]: any}>;

export function CheckUpdate():Promise<{[key: string]: any}>;

export function ClearLogs():Promise<boolean>;

export function GetLogs():Promise<Array<main.LogEntry>>;

export function GetStatus():Promise<{[key: string]: any}>;

export function GetUser():Promise<main.UserSession>;

export function GetVersion():Promise<string>;

export function Login(arg1:string,arg2:string):Promise<{[key: string]: any}>;

export function Logout():Promise<boolean>;

export function StartAgent():Promise<{[key: string]: any}>;

export function StopAgent():Promise<boolean>;
