#!/usr/bin/env node
/**
 * Build SocialFlow Agent exe
 * Reads .env → injects config into build → creates exe
 * Packages chromium-1208, chromium_headless_shell-1208, and ffmpeg-1011
 *
 * Usage: node scripts/build.js
 */
const fs = require('fs')
const path = require('path')
const { execSync } = require('child_process')

const ROOT = path.join(__dirname, '..')
const ENV_PATH = path.join(ROOT, '.env')
const CONFIG_PATH = path.join(ROOT, 'lib', 'config.js')

console.log('=== SocialFlow Agent Builder ===\n')

// 1. Read .env
if (!fs.existsSync(ENV_PATH)) {
  console.error('[ERROR] .env file not found!')
  process.exit(1)
}

// Tách theo CẢ \r\n lẫn \n. Trước đây chỉ tách '\n', nên .env lưu kiểu Windows
// (CRLF) làm hỏng TOÀN BỘ: trong regex JS, `.` không khớp `\r` nên `(.*)$`
// không bao giờ khớp nổi dòng còn sót `\r` ở cuối → 0 biến đọc được, và build
// chỉ báo cụt lủn "Missing required env var: API_URL" khiến rất khó đoán.
// Bỏ BOM ở đầu file vì trình soạn thảo Windows hay thêm vào.
const envContent = fs.readFileSync(ENV_PATH, 'utf8').replace(/^﻿/, '')
const envVars = {}
for (const line of envContent.split(/\r?\n/)) {
  const match = line.match(/^\s*([^#=]+?)\s*=\s*(.*)$/)
  if (match) envVars[match[1].trim()] = match[2].trim()
}

// Accept either AGENT_SECRET (canonical, matches API server) or AGENT_SECRET_KEY (legacy)
const agentSecret = envVars.AGENT_SECRET || envVars.AGENT_SECRET_KEY
if (!envVars.API_URL) {
  console.error('[ERROR] Missing required env var: API_URL')
  process.exit(1)
}
if (!agentSecret) {
  console.error('[ERROR] Missing required env var: AGENT_SECRET (or AGENT_SECRET_KEY)')
  process.exit(1)
}

console.log('[OK] .env loaded')
console.log(`  API_URL: ${envVars.API_URL}`)
console.log('  AGENT_ID: sinh riêng theo từng máy lúc chạy (không nướng vào bản build)')

// 2. Generate config.js with embedded credentials (no Supabase)
//
// CỐ Ý KHÔNG nhúng AGENT_ID: nhúng vào thì mọi máy cài từ cùng một file .exe
// đều mang chung một tên agent → chung dòng heartbeat, tranh job của cùng
// nick, hai máy cùng mở trình duyệt trên một nick từ hai IP (Facebook bắt
// checkpoint). Mã máy giờ sinh lúc chạy và lưu tại ~/.socialflow-machine-id
// (xem lib/agent-id.js). Muốn đặt tên chủ động thì dùng biến môi trường
// AGENT_ID trên chính máy đó.
const configContent = `// Auto-generated by build script — DO NOT EDIT
// These credentials are embedded at build time
module.exports = {
  FRONTEND_URL: ${JSON.stringify(envVars.FRONTEND_URL || 'https://app-103-142-24-60.sslip.io')},
  API_URL: ${JSON.stringify(envVars.API_URL || '')},
  AGENT_SECRET_KEY: ${JSON.stringify(agentSecret)},
  DISABLE_WARMUP: ${JSON.stringify(envVars.DISABLE_WARMUP || '')},
  HEADLESS: ${JSON.stringify(envVars.HEADLESS || '')},
}
`
fs.writeFileSync(CONFIG_PATH, configContent)
console.log('[OK] lib/config.js generated')

// 2.5 Copy local Playwright browser binaries if they exist
const os = require('os')
const localAppData = process.env.LOCALAPPDATA || path.join(os.homedir(), 'AppData', 'Local')
const playwrightSrc = path.join(localAppData, 'ms-playwright')
const playwrightDest = path.join(ROOT, 'ms-playwright')

if (fs.existsSync(playwrightSrc)) {
  console.log('[BUILD] Copying local Playwright browsers to bundle...')
  fs.mkdirSync(playwrightDest, { recursive: true })
  
  const requiredFolders = ['chromium-1208', 'chromium_headless_shell-1208', 'ffmpeg-1011']
  for (const folder of requiredFolders) {
    const srcPath = path.join(playwrightSrc, folder)
    const destPath = path.join(playwrightDest, folder)
    if (fs.existsSync(srcPath)) {
      if (!fs.existsSync(destPath)) {
        console.log(`  Copying ${folder}... (this may take a moment)`)
        fs.cpSync(srcPath, destPath, { recursive: true })
      } else {
        console.log(`  Already copied: ${folder}`)
      }
    } else {
      console.warn(`  [WARN] Source path not found for required folder: ${srcPath}`)
    }
  }
} else {
  console.log('[WARN] Local ms-playwright directory not found, browser binaries cannot be packaged!')
}

// 3. Build with electron-builder
console.log('\n[BUILD] Creating exe...')
try {
  execSync('npx electron-builder --win nsis --config.win.signAndEditExecutable=false', {
    cwd: ROOT,
    stdio: 'inherit',
    shell: true,
    env: { ...process.env, CSC_IDENTITY_AUTO_DISCOVERY: 'false', WIN_CSC_LINK: '' },
  })
  console.log('\n[OK] Build complete!')
} catch (err) {
  console.error('\n[ERROR] Build failed:', err.message)
  fs.unlinkSync(CONFIG_PATH)
  process.exit(1)
}

// 4. Clean up
fs.unlinkSync(CONFIG_PATH)
console.log('[OK] Cleaned up lib/config.js from source')

// 5. Show result
const distDir = path.join(ROOT, 'dist')
const exeFiles = fs.readdirSync(distDir).filter(f => f.endsWith('.exe') && !f.includes('unpacked'))
if (exeFiles.length > 0) {
  const exePath = path.join(distDir, exeFiles[0])
  const size = (fs.statSync(exePath).size / 1024 / 1024).toFixed(1)
  console.log(`\n=== Build Output ===`)
  console.log(`  EXE: ${exeFiles[0]} (${size} MB)`)
  console.log(`  Credentials: embedded (no .env needed)`)
  console.log(`\nUser just double-clicks the exe and it works!`)
}
