#!/usr/bin/env node
/**
 * Build SocialFlow Agent exe
 * Reads .env → injects config into build → creates exe
 *
 * Usage: node scripts/build.js
 */
const fs = require('fs')
const path = require('path')
const { execSync } = require('child_process')

const ROOT = path.join(__dirname, '..')
const ENV_PATH = path.join(ROOT, '.env')
const CONFIG_PATH = path.join(ROOT, 'lib', 'config.js')

console.log('=== SocialFlow Agent Builder ===\n')

// 1. Read .env
if (!fs.existsSync(ENV_PATH)) {
  console.error('[ERROR] .env file not found! Create .env with Supabase credentials first.')
  process.exit(1)
}

const envContent = fs.readFileSync(ENV_PATH, 'utf8')
const envVars = {}
for (const line of envContent.split('\n')) {
  const match = line.match(/^\s*([^#=]+?)\s*=\s*(.*)$/)
  if (match) envVars[match[1].trim()] = match[2].trim()
}

// Validate required vars
const required = ['SUPABASE_URL', 'SUPABASE_SERVICE_ROLE_KEY']
for (const key of required) {
  if (!envVars[key]) {
    console.error(`[ERROR] Missing required env var: ${key}`)
    process.exit(1)
  }
}

console.log('[OK] .env loaded')
console.log(`  SUPABASE_URL: ${envVars.SUPABASE_URL}`)
console.log(`  AGENT_ID: ${envVars.AGENT_ID || '(auto-generated)'}`)

// 2. Generate config.js with embedded credentials
const configContent = `// Auto-generated by build script — DO NOT EDIT
// These credentials are embedded at build time
module.exports = {
  SUPABASE_URL: ${JSON.stringify(envVars.SUPABASE_URL || '')},
  SUPABASE_SERVICE_ROLE_KEY: ${JSON.stringify(envVars.SUPABASE_SERVICE_ROLE_KEY || '')},
  SUPABASE_ANON_KEY: ${JSON.stringify(envVars.SUPABASE_ANON_KEY || '')},
  FRONTEND_URL: ${JSON.stringify(envVars.FRONTEND_URL || 'https://socialflow-bice.vercel.app')},
  AGENT_ID: ${JSON.stringify(envVars.AGENT_ID || '')},
}
`
fs.writeFileSync(CONFIG_PATH, configContent)
console.log('[OK] lib/config.js generated with embedded credentials')

// 3. Build with electron-builder (uses asarUnpack config from package.json)
console.log('\n[BUILD] Creating exe...')
try {
  execSync('npx electron-builder --win portable --config.win.signAndEditExecutable=false', {
    cwd: ROOT,
    stdio: 'inherit',
    shell: true,
    env: { ...process.env, CSC_IDENTITY_AUTO_DISCOVERY: 'false', WIN_CSC_LINK: '' },
  })
  console.log('\n[OK] Build complete!')
} catch (err) {
  console.error('\n[ERROR] Build failed:', err.message)
  fs.unlinkSync(CONFIG_PATH)
  process.exit(1)
}

// 4. Clean up — remove config.js from source (it's inside the exe now)
fs.unlinkSync(CONFIG_PATH)
console.log('[OK] Cleaned up lib/config.js from source')

// 5. Show result
const distDir = path.join(ROOT, 'dist')
const exeFiles = fs.readdirSync(distDir).filter(f => f.endsWith('.exe') && !f.includes('unpacked'))
if (exeFiles.length > 0) {
  const exePath = path.join(distDir, exeFiles[0])
  const size = (fs.statSync(exePath).size / 1024 / 1024).toFixed(1)
  console.log(`\n=== Build Output ===`)
  console.log(`  EXE: ${exeFiles[0]} (${size} MB)`)
  console.log(`  Credentials: embedded (no .env needed)`)
  console.log(`\nUser just double-clicks the exe and it works!`)
}
