#!/usr/bin/env node
/**
 * Build SocialFlow Agent exe
 * Reads .env → injects config into build → creates exe
 *
 * Usage: node scripts/build.js
 */
const fs = require('fs')
const path = require('path')
const { execSync } = require('child_process')

const ROOT = path.join(__dirname, '..')
const ENV_PATH = path.join(ROOT, '.env')
const CONFIG_PATH = path.join(ROOT, 'lib', 'config.js')

console.log('=== SocialFlow Agent Builder ===\n')

// 1. Read .env
if (!fs.existsSync(ENV_PATH)) {
  console.error('[ERROR] .env file not found!')
  process.exit(1)
}

const envContent = fs.readFileSync(ENV_PATH, 'utf8')
const envVars = {}
for (const line of envContent.split('\n')) {
  const match = line.match(/^\s*([^#=]+?)\s*=\s*(.*)$/)
  if (match) envVars[match[1].trim()] = match[2].trim()
}

// Accept either AGENT_SECRET (canonical, matches API server) or AGENT_SECRET_KEY (legacy)
const agentSecret = envVars.AGENT_SECRET || envVars.AGENT_SECRET_KEY
if (!envVars.API_URL) {
  console.error('[ERROR] Missing required env var: API_URL')
  process.exit(1)
}
if (!agentSecret) {
  console.error('[ERROR] Missing required env var: AGENT_SECRET (or AGENT_SECRET_KEY)')
  process.exit(1)
}

console.log('[OK] .env loaded')
console.log(`  API_URL: ${envVars.API_URL}`)
console.log(`  AGENT_ID: ${envVars.AGENT_ID || '(auto-generated)'}`)

// 2. Generate config.js with embedded credentials (no Supabase)
const configContent = `// Auto-generated by build script — DO NOT EDIT
// These credentials are embedded at build time
module.exports = {
  FRONTEND_URL: ${JSON.stringify(envVars.FRONTEND_URL || 'https://socialflow888.vercel.app')},
  AGENT_ID: ${JSON.stringify(envVars.AGENT_ID || '')},
  API_URL: ${JSON.stringify(envVars.API_URL || '')},
  AGENT_SECRET_KEY: ${JSON.stringify(agentSecret)},
}
`
fs.writeFileSync(CONFIG_PATH, configContent)
console.log('[OK] lib/config.js generated')

// 3. Build with electron-builder
console.log('\n[BUILD] Creating exe...')
try {
  execSync('npx electron-builder --win portable --config.win.signAndEditExecutable=false', {
    cwd: ROOT,
    stdio: 'inherit',
    shell: true,
    env: { ...process.env, CSC_IDENTITY_AUTO_DISCOVERY: 'false', WIN_CSC_LINK: '' },
  })
  console.log('\n[OK] Build complete!')
} catch (err) {
  console.error('\n[ERROR] Build failed:', err.message)
  fs.unlinkSync(CONFIG_PATH)
  process.exit(1)
}

// 4. Clean up
fs.unlinkSync(CONFIG_PATH)
console.log('[OK] Cleaned up lib/config.js from source')

// 5. Show result
const distDir = path.join(ROOT, 'dist')
const exeFiles = fs.readdirSync(distDir).filter(f => f.endsWith('.exe') && !f.includes('unpacked'))
if (exeFiles.length > 0) {
  const exePath = path.join(distDir, exeFiles[0])
  const size = (fs.statSync(exePath).size / 1024 / 1024).toFixed(1)
  console.log(`\n=== Build Output ===`)
  console.log(`  EXE: ${exeFiles[0]} (${size} MB)`)
  console.log(`  Credentials: embedded (no .env needed)`)
  console.log(`\nUser just double-clicks the exe and it works!`)
}
